apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: clone-task
spec:
  inputs:
    params:
      - name: repository
        description: the git repo
      - name: revision
        description: the revision
        default: master  
      - name: pvc-name
        description: the output pvc
      - name: pvc-sub-path
        description: the path where the repo should be cloned
        default: ""  
  steps:
    - name: clone-repo
      image: alpine/git
      env:
        - name: REPOSITORY
          value: $(inputs.params.repository)
        - name: REVISION
          value: $(inputs.params.revision)
      command: ["/bin/sh", "-c"]
      args:
        - set -e -o pipefail;
          echo "Cloning $REPOSITORY";
          git clone -q -b $REVISION $REPOSITORY /dest;
      volumeMounts:
        - mountPath: /dest
          name: clone-volume
          subPath: $(inputs.params.pvc-sub-path)
  volumes:
    - name: clone-volume
      persistentVolumeClaim:
        claimName: $(inputs.params.pvc-name)